### ISSUE TITLE
[Question]: Anyway we can setup r-universe so it keeps archives of packages?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/nestdevs-tasks#55] opened 2024-05-22 19:58 UTC
I am working on setting up a `pak` `.lockfile` that would allow to reproduce the session in which `teal` shiny app is running. https://github.com/insightsengineering/coredev-tasks/issues/479 and I figured out we may want to setup an archive for r-universe.dev R archive network.

Imagine someone installed `teal.reporter`  from https://pharmaverse.r-universe.dev/teal.reporter on a specific day and got version `0.3.1.9006`. Then created a `teal` app and exposed it with a possibility to see session info and `pack` `.lockfile`.

Now imagine we merge features and fixes to `main` branch on https://github.com/insightsengineering/teal.reporter/ repository. This means that `teal.reporter` gets a vbump and a new development version is pushed to https://pharmaverse.r-universe.dev/teal.reporter and the old one `0.3.1.9006` is removed (from https://pharmaverse.r-universe.dev/teal.reporter), because we do not keep track of previous packages (we do not keep the archive of packages).  

It is then impossible to restore the session from the mentioned `teal` app that is based on `teal.reporter` `0.3.1.9006` because r-universe no longer have this version. `pak` has no way to figure out that you can also install `teal.reporter` from Github because the session info and the `.lockfile` present the source of `teal.reporter` installation which is https://pharmaverse.r-universe.dev/teal.reporter

**Comment by m7pr** [comment] 2024-05-22 19:59
CC @pawelru @gogonzo @donyunardi

**Comment by m7pr** [comment] 2024-05-22 20:09
Btw a hilarious Details information from `pak::lockfile_create`

<img width="710" alt="image" src="https://github.com/insightsengineering/nestdevs-tasks/assets/133694481/4a3ea453-21d2-4cfa-b17a-95cff5778a6e">

**Comment by pawelru** [comment] 2024-05-23 07:11
To the best of my knowledge, this is not possible by design and there is nothing we can do about that. That's a known limitation of creating snapshot consisting of packages installed from r-universe.
The only solution I'm seeing is installing from long-persisting sources such as GH or CRAN / CRAN-like repos.

**Comment by m7pr** [comment] 2024-05-23 11:27
What if we support drat-like archive, and keep pushing new releases? From the user perspective it's an `install.packages` call but with a different `repos` argument which is copied anyway. Òn our end we would need to setup:
- address for drat-like repositories
- create jobs that would update drat-like repositories

In the current setup `r-universe` does not bring much value besides testing on multiple platforms. It does not support reproducibility.

**Comment by pawelru** [comment] 2024-05-23 12:22
We used to have this some time ago. It's there: https://github.com/insightsengineering/depository

This was abandoned for the reasons I cannot recall I am afraid. @cicdguy do you happen to remember what was bad about this?

> In the current setup r-universe does not bring much value besides testing on multiple platforms. It does not support reproducibility.

There are number of features that are quite cool actually - binaries for wasm or binaries for devel state of package to faster install deps in CI. For reproducibility you are right. That's why it needs to be used only when repro is not required. We knew this from the very beginning.

**Comment by vedhav** [comment] 2024-05-23 13:01
I think this will never be possible using [r-universe](https://ropensci.org/blog/2022/01/06/runiverse-renv/#why-r-universe-is-not-an-archive). Also, it's going to be an overkill. The only feasible way to achieve dev package install is by building them from source from the GitHub repos.

**Comment by vedhav** [comment] 2024-05-23 13:02
Back in the day, we were hitting API rate limits because all the repos were being downloaded from GiHub. But, now with the CRAN release this should not be the case if only few packages are being installed from GitHub API. I think this was also the problem with depository.

**Comment by m7pr** [comment] 2024-05-23 13:23
> Anyway we can setup r-universe so it keeps archives of packages?

This is not the real question honestly. This is just a nudge to move towards a solution that supports having past versions of packages. drat helps creating such networks/archives

**Comment by vedhav** [comment] 2024-05-23 13:55
> This is not the real question honestly.

haha of course! With some money we can do anything we want 🤑. The closest thing I can think of is to get a [PPM](https://packagemanager.posit.co/client/#/) and release on main merge like we do in our internal package manager.

**Comment by pawelru** [comment] 2024-11-01 09:19
I feel that the question had been already answered. Closing.

**Closed by pawelru** 2024-11-01 09:19 UTC
Labels: question, core
