### ISSUE TITLE
Teal how-to series

### ISSUE THREAD

**Issue by asbates** [insightsengineering/nestdevs-tasks#15] opened 2023-03-28 17:31 UTC
Not sure if we would want to do this as part of CRAN release so I put this in a new issue.

I'm thinking it could be helpful to have a series of tutorials on teal. Starting with the bare minimum. Then add quenv, then reporter, then ... I know we kind of have this with vignettes but there's not a clear order and not a clear build up.

Maybe this could be a bookdown or even a video series.

**Comment by asbates** [comment] 2023-03-29 16:50
A couple of ideas on how this could go.

Start with the absolute simplest example of a teal application. The next section would then introduce `teal.code` and `qenv` through an example app, adding it to the original simple application. Then `teal.slice` and the filtering could be introduced, again adding it to the original application, but not including the `teal.code` parts from the second example. The idea here is that features are introduced independently, one at a time.


The next idea is having an end goal application that gets slowly built up. This could be a complex example with multiple modules, reporting, etc. We could show the app first allowing people to see what the goal is. Then each lesson builds on the last, working our way up to the final application.

**Comment by donyunardi** [comment] 2023-10-26 18:59
This issue felt very similar with what we're trying to achieve in https://github.com/insightsengineering/teal/issues/807

We'll make sure to include the topic of creating shiny module where qenv and reporter topics will be covered.

**Comment by donyunardi** [comment] 2023-10-26 19:02
Closing, duplicate of https://github.com/insightsengineering/teal/issues/807

**Closed by donyunardi** 2023-10-26 19:02 UTC
Labels: documentation, core
